### ISSUE TITLE
The `allowRules` option is missing in the types and documentation

### ISSUE THREAD

**Issue by zoxon** [GoogleChromeLabs/critters#137] opened 2023-09-19 09:54 UTC
Please add `allowRules` into types definition and docs
https://github.com/GoogleChromeLabs/critters/blob/main/packages/critters/src/index.js#L126

**Comment by kara** [comment] 2024-10-25 18:23
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:23 UTC
