### ISSUE TITLE
Adding Critters to project removes media queries from external stylesheet

### ISSUE THREAD

**Issue by richiksc** [GoogleChromeLabs/critters#34] opened 2019-04-09 16:41 UTC
I'm using Critters in my webpack project with the following configuration:

```js
new Critters({
  mergeStylesheets: true,
  inlineFonts: true,
})
```
I'm using this in combination with MiniCssExtractPlugin. When I add Critters to the plugin list (after MiniCssExtractPlugin and HtmlWebpackPlugin), critters seems to remove the content of media queries - the output still has the media queries but nothing is in them, which looks like this:

```css
@media (max-width: 480px) {}
```

This breaks the styling and layout of my site.

**Comment by fpapado** [comment] 2019-04-09 18:03
Hi @richiksc, I think this is because the `pruneSource` is `true` by default. I had the same issue, and turning it to `false` fixed it.

(The option is documented here: https://github.com/GoogleChromeLabs/critters/blob/master/README.md#critters-2)

Removing the inlined CSS from the source doesn't make a large difference in my experience, so I don't think you'd lose much without it. 

Posting this in case it gets you unblocked :) I'm not one of the maintainers, but I'm curious if there's a bug to file about this.

**Comment by richiksc** [comment] 2019-04-09 18:34
Not pruning the source makes adds unneccessary weight to the external stylesheet, which means the browser has to download those extra bytes from the network, increasing the page weight and slowing the experience down.

**Comment by fpapado** [comment] 2019-04-09 21:06
I know, I was mentioning it in case it was something actionable; I don't know the app you are building, not pruning could very well have a large effect there :)

For the maintainers: I've also had this issue when pruneSource is on.

**Comment by jaydiablo** [comment] 2019-07-08 16:41
I can also confirm that changing `pruneSource` from `true` (the default) to `false` fixes the issue of CSS inside media queries being removed.

**Comment by developit** [comment] 2019-11-01 21:27
I'd actually generally recommend turning `pruneSource` off, regardless of this bug. Pruning source CSS in a multipage website can be really bad for caching and occasionally fails entirely. If each page on a website has different markup, the inlined CSS rules are different for each page, which means the pruned external CSS is different depending on which page you visit. The effect is that it's not really possible to cache CSS when pruning in a multi-page setup.

This is not as much of an issue for Single Page Apps, which is why the default value is `true`.

As for the bug here, it's something relating to how the [mirrored rule traversal](https://github.com/GoogleChromeLabs/critters/blob/4aebce41af8a8ae2b775f9b58a922b15a289fe30/src/index.js#L451-L453) [descends into nested rules](https://github.com/GoogleChromeLabs/critters/blob/4aebce41af8a8ae2b775f9b58a922b15a289fe30/src/css.js#L87-L89). My guess is that, since there's no logic currently in the walk to deal with media queries, it's considering *all* media queries to be critical, and pruning them from the original external CSS.

**Comment by kara** [comment] 2024-10-25 18:20
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:20 UTC
Labels: bug, help wanted, good first issue
