### ISSUE TITLE
Branching webpack versions

### ISSUE THREAD

**Issue by echolimazulu** [GoogleChromeLabs/critters#107] opened 2022-07-01 08:02 UTC
Hello @developit and other contributors,

There is currently a dependency on `"html-webpack-plugin": "^4.5.2"`. Version `4.5.2` is used with webpack version 4. It may make sense to branch along the same lines as implemented in `html-webpack-plugin` with the plugin version specified via `@`:
**for webpack5** - critters-webpack-plugin
**for webpack4** - critters-webpack-plugin@4

https://github.com/GoogleChromeLabs/critters/blob/a590c05f9197b656d2aeaae9369df2483c26b072/packages/critters-webpack-plugin/package.json#L63

On webpack version 5, I didn't notice any major compatibility issues.

**Comment by kara** [comment] 2024-10-25 18:22
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:22 UTC
