### ISSUE TITLE
Error when using selector ::part, Unmatched selector and :host-context([dir=rtl]) subselects_1.subselects[name] is not a function

### ISSUE THREAD

**Issue by odaialsughier** [GoogleChromeLabs/critters#99] opened 2022-02-02 13:18 UTC
I was building my ionic project when i got this warning 

> Generating index html...16 rules skipped due to selector errors:
>   .ma-input-field::part(native) -> Unmatched selector: )
>   .item.ma-input-field::part(native) -> Unmatched selector: )
>   ion-range::part(bar) -> Unmatched selector: )
>   ion-range::part(bar-active) -> Unmatched selector: )
>   ion-range::part(knob) -> Unmatched selector: )
>   .list-item--top-level::part(detail-icon) -> Unmatched selector: )
>   :host-context([dir=rtl]) .ion-float-start -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-end -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-sm-start -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-sm-end -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-md-start -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-md-end -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-lg-start -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-lg-end -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-xl-start -> subselects_1.subselects[name] is not a function
>   :host-context([dir=rtl]) .ion-float-xl-end -> subselects_1.subselects[name] is not a function

the warning is happening in utils.bundle.css inside the @ionic/angular bundle

**Comment by kara** [comment] 2024-10-25 18:21
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:21 UTC
