### ISSUE TITLE
Compilation asset keys (path) don't mach on Windows (Unable to locate stylesheet)

### ISSUE THREAD

**Issue by boardend** [GoogleChromeLabs/critters#58] opened 2020-06-22 12:20 UTC
On Windows 10 (CMD/PowerShell/Git Bash) the latest Critters version (1.3.5) is "Unable to locate stylesheet", but the same setup works without problems on a Unix-like system / WSL 2.

I think the problem is, that the path gets normalized in the "compilation.assets"-keys, but not in embedLinkedStylesheet. Here is the state in [embedLinkedStylesheet](https://github.com/GoogleChromeLabs/critters/blob/master/src/index.js#L278) on **WSL2**:
```
{
  outputPath: '/home/USERNAME/dev/git/PROJECT-ui/PROJECT/app/PROJECT-app-PROJECT2-dev/dist',
  normalizedPath: 'css/chunk-vendors.3a56f9b8.css',
  filename: '/home/USERNAME/dev/git/PROJECT-ui/PROJECT/app/PROJECT-app-PROJECT2-dev/dist/css/chunk-vendors.3a56f9b8.css',
  relativePath: 'css/chunk-vendors.3a56f9b8.css',
  compilationAssetKeys: [
    'css/chunk-vendors.3a56f9b8.css',
    [...60 lines omitted...]
 ]
}
```
And the same commit, but with a clone on **Windows in PowerShell**:
```
{
  outputPath: 'C:\\dev\\git\\PROJECT-ui\\PROJECT\\app\\PROJECT-app-PROJECT2-dev\\dist',
  normalizedPath: 'css/chunk-vendors.3a56f9b8.css',
  filename: 'C:\\dev\\git\\PROJECT-ui\\PROJECT\\app\\PROJECT-app-PROJECT2-dev\\dist\\css\\chunk-vendors.3a56f9b8.css',
  relativePath: 'css\\chunk-vendors.3a56f9b8.css',
  compilationAssetKeys: [
    'css/chunk-vendors.3a56f9b8.css',
    [...60 lines omitted...]
 ]
}
```
so `compilation.assets[relativePath]` won't match, which will produce the following error:
```
‼ ｢Critters｣: Unable to locate stylesheet: css\chunk-vendors.3a56f9b8.css
```

**Comment by developit** [comment] 2020-08-23 19:22
Ahh, good catch. We can definitely get this fixed, I'm now working part-time on a windows machine so its easier to test.

**Comment by kara** [comment] 2024-10-25 18:21
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:21 UTC
Labels: bug, help wanted, good first issue, webpack
