### ISSUE TITLE
Non-matching selectors for a declaration block get pruned, but do not get inlined

### ISSUE THREAD

**Issue by dominykas** [GoogleChromeLabs/critters#49] opened 2020-01-08 11:35 UTC
Suppose your stylesheet has `body, html, div, p { margin: 0; padding: 0 }`, but your document does not have a `p`. The produced inline stylesheet will only have `body, html, div`, but the original stylesheet will have the whole declaration block removed, leaving your `p`s that you add dynamically unstyled.

**Comment by dominykas** [comment] 2020-01-08 11:53
I only started poking around to see if I can fix this myself to spot this commit: https://github.com/GoogleChromeLabs/critters/commit/1f9fd6628753a159579ac4718de25f89fa25acf3 - could it be the culprit?

**Comment by Desires01-dev** [comment] 2020-01-15 05:39
Be right hear ,git your back some resporties hQ migration certificate global jams been fight with one steal identity theaft everything griffina emulator Google chrome Apple Mack been finding ways keep non profit, sharing holding global jams branches get paid as well

**Comment by kara** [comment] 2024-10-25 18:21
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:21 UTC
Labels: bug
