### ISSUE TITLE
Animation keyframe detection is not using the correct index in the iterator [v1.3.3]

### ISSUE THREAD

**Issue by pathacks** [GoogleChromeLabs/critters#40] opened 2019-09-02 03:41 UTC
For any CSS where there is animation declarations, the library will throw an error if the index `i` is out of bounds of the Array of critical keyframe names, since it should be iterating using index `j` instead.

This issue was addressed in [this commit](https://github.com/GoogleChromeLabs/critters/commit/aba56056464768f599703201f655328b07c61b4a) which was released in v2.4.0, however this fix was never applied to the 1.x codeline, of which there are several very popular packages still using it (e.g. [preact-cli](https://github.com/preactjs/preact-cli))

Can we please have a hotfix release for 1.x, with that fix included?

**Comment by kara** [comment] 2024-10-25 18:21
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:21 UTC
Labels: 1.x
