### ISSUE TITLE
Unable to locate stylesheet

### ISSUE THREAD

**Issue by echolimazulu** [GoogleChromeLabs/critters#106] opened 2022-07-01 06:10 UTC
Hello @developit and other contributors,

Thanks to you and the contributors of this project for a job well done.

While working with the **critters-webpack-plugin** project on macOS, I found that the `this.compilation` argument was probably redundant, resulting in an exception:
https://github.com/GoogleChromeLabs/critters/blob/a590c05f9197b656d2aeaae9369df2483c26b072/packages/critters-webpack-plugin/src/index.js#L172

I can assume that this is a bug, since readFile:
https://github.com/GoogleChromeLabs/critters/blob/a590c05f9197b656d2aeaae9369df2483c26b072/packages/critters/src/index.d.ts#L33 https://github.com/GoogleChromeLabs/critters/blob/a590c05f9197b656d2aeaae9369df2483c26b072/packages/critters/src/index.js#L141

When the specified argument is removed, the assembly works properly.

**Plugin version is 3.0.2., Webpack version is 5.**

**Comment by janicklas-ralph** [comment] 2022-07-06 20:21
That makes sense to me. Could you open a PR with those changes and I can merge

**Comment by echolimazulu** [comment] 2022-07-07 07:52
@janicklas-ralph Good morning Janicklas,

Thank you for your attention to this issue.

Please give me some time so that I can take a closer look at this issue, after which I can offer a PR.

**Comment by echolimazulu** [comment] 2022-07-08 18:37
@janicklas-ralph Good evening,

Please check out the solution I provided in **PR**: https://github.com/GoogleChromeLabs/critters/pull/109

**Comment by kara** [comment] 2024-10-25 18:22
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:22 UTC
