### ISSUE TITLE
Cannot read properties of undefined (reading 'setAttribute')

### ISSUE THREAD

**Issue by mgalasso** [GoogleChromeLabs/critters#135] opened 2023-08-04 20:28 UTC
**In Angular 16**, during a build (ng build), there is an unhandled error within critters.js:519:30

**Here is the code snippet within critters.js:**
  if (!crittersContainer) {
    document.documentElement.setAttribute('data-critters-container', '');
    crittersContainer = document.documentElement;
  }

**Here is the error message:**
[error] TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at createDocument (C:\Development\sourcecode\sequoia\node_modules\critters\dist\critters.js:519:30)
    at CrittersExtended.process (C:\Development\sourcecode\sequoia\node_modules\critters\dist\critters.js:1123:22)
    at InlineCriticalCssProcessor.process (C:\Development\sourcecode\sequoia\node_modules\@angular-devkit\build-angular\src\utils\index-file\inline-critical-css.js:167:40)
    at C:\Development\sourcecode\sequoia\node_modules\@angular-devkit\build-angular\src\utils\index-file\index-html-generator.js:123:64
    at IndexHtmlGenerator.process (C:\Development\sourcecode\sequoia\node_modules\@angular-devkit\build-angular\src\utils\index-file\index-html-generator.js:65:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execute (C:\Development\sourcecode\sequoia\node_modules\@angular-devkit\build-angular\src\builders\browser-esbuild\index.js:107:47)
    at async withSpinner (C:\Development\sourcecode\sequoia\node_modules\@angular-devkit\build-angular\src\tools\esbuild\utils.js:73:16)
    at async buildEsbuildBrowserInternal (C:\Development\sourcecode\sequoia\node_modules\@angular-devkit\build-angular\src\builders\browser-esbuild\index.js:207:18)
    at async handleAsyncIterator (C:\Development\sourcecode\sequoia\node_modules\@angular-devkit\architect\src\api.js:35:28)

**As a consequence**, the index.html cannot be built within the Angular project. (Index html generation failed.)

**Comment by scifresh** [comment] 2023-08-24 20:30
i get a similar one

`✖ Index html generation failed.
document.documentElement.setAttribute is not a function`

**Comment by marco910** [comment] 2023-09-14 13:38
I'm facing the same issue in Next.js 13 and `critters@0.0.20`. It only happens with server-side rendering in some cases

**Comment by TheElegantCoding** [comment] 2023-12-30 03:30
same here in vite

**Comment by saenif** [comment] 2024-02-14 08:43
same like @scifresh

**Comment by briouyaasmae** [comment] 2024-03-13 14:03
Same here with Angular 17

**Comment by KRS-envisageworld** [comment] 2024-06-08 11:30
Also, facing the same issue while building the application. Does anyone know the root cause of this error?

**Comment by kara** [comment] 2024-10-25 18:23
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:23 UTC
