### ISSUE TITLE
Macbook M3 Sequoia: On Angular 18 new APP's: An unhandled exception occurred: Cannot find module 'postcss-media-query-parser'

### ISSUE THREAD

**Issue by aleftos** [GoogleChromeLabs/critters#175] opened 2024-10-03 16:17 UTC
Macbook M3 - Sequoia, Angular 18
ng serve
An unhandled exception occurred: Cannot find module 'postcss-media-query-parser'

[error] Error: Cannot find module 'postcss-media-query-parser'
Require stack:
- node_modules/critters/dist/critters.js
- node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/utils/index-file/inline-critical-css.js
- node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/utils/index-file/index-html-generator.js
- node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/tools/esbuild/index-html-generator.js
- node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/builders/application/execute-post-bundle.js
- node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/builders/application/execute-build.js
- node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/builders/application/index.js
- node_modules/@angular-devkit/build-angular/node_modules/@angular/build/src/private.js
- node_modules/@angular-devkit/build-angular/src/builders/dev-server/builder.js
- node_modules/@angular-devkit/build-angular/src/builders/dev-server/index.js
- node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (node_modules/critters/dist/critters.js:10:35)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1691:10)
    at Module.load (node:internal/modules/cjs/loader:1317:32)

**Comment by kara** [comment] 2024-10-25 18:24
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:24 UTC
