### ISSUE TITLE
Compress output using Parcel-CSS

### ISSUE THREAD

**Issue by developit** [GoogleChromeLabs/critters#98] opened 2022-01-13 15:16 UTC
Inlined styles should be compressed to deduplicate when multiple stylesheet sources are used. We removed this in the refactor because cssnano was too slow, but it looks like [parcel-css is 10x faster](https://github.com/parcel-bundler/parcel-css#benchmarks) and could be used.

**Comment by kara** [comment] 2024-10-25 18:21
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:21 UTC
