### ISSUE TITLE
Building Angular 17.1 with Angular CLI when using Bootstrap 5.3.2 results in Critical CSS Inlining failing because 2 rules are skipped due to selector errors

### ISSUE THREAD

**Issue by elezar42** [GoogleChromeLabs/critters#153] opened 2024-01-25 01:56 UTC
The 2 rules are the same rule listed twice:
```
- Generating index html...2 rules skipped due to selector errors:
  .form-floating>~label -> Did not expect successive traversals.
  .form-floating>~label -> Did not expect successive traversals.
```

`>~` is obviously an invalid selector, however it doesn't look like that's ever actually used in the Bootstrap code. I've checked myself, and one of the bootstrap devs has also confirmed it twbs/bootstrap#39323. The base style is simply `.form-floating > label` while there are a number of styles in the format of `.form-floating > [another selector] ~ label`.  It seems one of those intermediary selectors is being removed during CSS processing.

There is a workaround of disabled Inlining of Critical CSS, but of course we're then missing out on a possible performance improvement.

This was reported as an Issue with Angular CLI last year, but they indicated it is a problem with Critters: https://github.com/angular/angular-cli/issues/25725#issuecomment-1697362593.

**Comment by eilzee** [comment] 2024-01-26 20:26
Even in the empty angular 17.1.0 project I get some errors

![Screenshot 2024-01-26 232318](https://github.com/GoogleChromeLabs/critters/assets/106151778/20b430c1-c5a9-4f16-9aeb-65cd2cab5439)

**Comment by DanielHabenicht** [comment] 2024-02-23 16:24
Chipping in from the ng-bootstrap repo, where there was also a bug filed last year about this problem and it was resolved intermittently by critters version `0.0.18`. 
As it now resurfaces this likely is a regression. 
I saw the warnings with `@angular-devkit/build-angular:17.2.1` which references critters at version `0.0.20`,

**Comment by DanielHabenicht** [comment] 2024-02-23 16:27
This issue probably can be closed as duplicate of #103

**Comment by PowerKiKi** [comment] 2024-02-24 03:04
While the error looks similar, this issue is **not** a duplicate of #103. Because the whole project was heavily refactored in #124, specifically to solve #103. So it is unlikely to be the same root cause, and this issue needs its own proper investigation.

**Comment by schneefeldio** [comment] 2024-02-24 17:54
Same on my side. Setup an Angular ssr project from scratch including bootstrap and get exactly the same output running ng build.

![Uploading warnings.png…]()

**Comment by leandrotassi** [comment] 2024-02-29 16:58
I'm also having the same problem.

**Comment by eiswind** [comment] 2024-03-06 17:13
I see a lot of similar errors with picocss in Angular 17.2. For the moment I set "inlineCritical": false to have a working build.

**Comment by jitterbox** [comment] 2024-05-08 14:42
We're adding SSR to our legacy Angular project after upgrading to Angular v17.3.6, and it's now crashing the server-side node app due to looping selector errors (both with Vite dev server and express production app builds). The CSS styles are Telerik's, which may be hard to mitigate:
```
Angular is running in development mode.
7 rules skipped due to selector errors:
  .k-input-label:dir(rtl) -> Unknown pseudo-class :dir
```
Besides the "inlineCritical" workaround, which doesn't seem(?) to work initially, I saw that the Angular team commented on maybe finding a temporary solution that involves pinning a working Critters version... can anyone here indicate what version that should be, as well as whether this is targeted for a near-term fix?

**Comment by waterplea** [comment] 2024-05-29 08:19
Here's a case where it fails on a valid, albeit deprecated selector that we have to use because we need Safari 13 (only Safari 14 supports `:is(  )`, we have to use `-webkit-any(  )`:
https://github.com/taiga-family/taiga-ui/issues/7565

**Comment by KasunNi** [comment] 2024-07-08 04:38
I'm getting same warning after upgrade my angular 17.3.0 to 18.0.6

**Comment by kara** [comment] 2024-10-25 18:24
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:24 UTC
