### ISSUE TITLE
Disable font-face exclusion

### ISSUE THREAD

**Issue by ThornWalli** [GoogleChromeLabs/critters#136] opened 2023-09-12 10:48 UTC
Hello,

is there any way I can stop font faces from being extracted?

Already did it with 

`/* critters:include start */` or `/* critters:include */`. I'm afraid that font-faces are basically touched, but unfortunately it makes problems for us.

Because in the code the `include` doesn`t seem to affect the font-faces.

https://github.com/GoogleChromeLabs/critters/blob/19476119082f12f120077137ab67a7c863944212/packages/critters/src/index.js#L506-L594

Would like to disable everything that has to do with fonts.

**Example:** We have x font faces in our HTML. These are then loaded in the client via `document.fonts`. 
But because Critter takes them out they are missing.

**Comment by kara** [comment] 2024-10-25 18:23
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:23 UTC
