### ISSUE TITLE
Parse include/exclude markers with @preserve or /*! hints

### ISSUE THREAD

**Issue by xumepadismal** [GoogleChromeLabs/critters#134] opened 2023-08-04 12:07 UTC
Some bundlers (in my case it's Angular CLI) minifies CSS before running critters. Therefore, any `/* critters:exclude */` comments got stripped. 

However, it's possible to preserve them using `/*! critters:exclude */` or `/* critters:exclude @preserve */` hints but in this case these markers are ignored by critters.

Would it be possible to implement a bit smarter parse logic to support these cases?

Thanks

**Comment by kara** [comment] 2024-10-25 18:23
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:23 UTC
