### ISSUE TITLE
Local font source is not recognized as valid

### ISSUE THREAD

**Issue by Rarst** [GoogleChromeLabs/critters#113] opened 2022-07-28 09:35 UTC
Only font faces having `src: url()` are treated as valid, so `src: local()` ones would always be considered invalid and dropped, even if they are detected as critical fonts.

```css
@font-face {
  font-family: "Alegreya-fallback";
  size-adjust: 101%;
  src: local("Times New Roman");
}
```

https://github.com/GoogleChromeLabs/critters/blob/a590c05f9197b656d2aeaae9369df2483c26b072/packages/critters/src/index.js#L568-L587

Related #112

**Comment by kara** [comment] 2024-10-25 18:22
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:22 UTC
