### ISSUE TITLE
Non-critical rules are erased from inline styles

### ISSUE THREAD

**Issue by Rarst** [GoogleChromeLabs/critters#112] opened 2022-07-28 08:50 UTC
I have some `@font-face` rules for size-adjusted fallback fonts, to reduce CLS while web fonts are loading.

Out of the box critters doesn't seem to consider them critical CSS to inline (I've tried with `inlineFonts`, no difference for some reason?).

However stranger thing happens if I explicitly include them in HTML - critters actively _erases_ them from style block.

So given following style in head:

```css
<style>
  * {
    color: red !important;
  }

  @font-face {
    font-family: "Alegreya-fallback";
    size-adjust: 101%;
    src: local("Times New Roman");
  }

  @font-face {
    font-family: "Alegreya SC-fallback";
    size-adjust: 113.6%;
    src: local("Times New Roman");
  }

  @font-face {
    font-family: "Alegreya Sans-fallback";
    size-adjust: 86.56%;
    src: local("Arial");
  }
</style>
```

What's left from it after critters pass is:

```css
<style>* {
    color: red !important
}</style>
```

The font-face rules are gone - they are not there, or in critical CSS, or anywhere.

The log says:
```
Inlined 54 B (11% of original 464 B) of inline CSS.
```
Which is... strange. Dropping _any_ CSS from inline style seems actively destructive? It's not elsewhere, to be loaded later, it's just gone.

From some experiments same happens with any "non-critical" rule, that is such for a class not used on a page.

**Comment by hiepxanh** [comment] 2022-07-28 10:04
![image](https://user-images.githubusercontent.com/16970990/181479619-beff368c-218c-4f54-92a0-52b05df26d95.png)
did you try 8 posibility here?

**Comment by Rarst** [comment] 2022-07-28 10:08
I don't see how inline head styles are related to preload, they are not links?

They are just processed in place (and merged with critical css, depending on `mergeStylesheets` options).

**Comment by hiepxanh** [comment] 2022-07-28 10:39
I believe that purpose of inline css. Since that is font inline, and it is not used yet, so it is not included. can you try just use that font in a div to see it is included or not?

**Comment by Rarst** [comment] 2022-07-28 10:50
That font _is_ used, detecting that is a separate problem, see #113 follow-up.

The issue here is _broadly_ that critters seems to erase non-critical rules from inline blocks, which is destructive operation. There is no other source of those rules to load or fall back on, they are just gone.

**Comment by chrisneven** [comment] 2024-04-11 10:56
@Rarst Did you manage to find a solution?

**Comment by Rarst** [comment] 2024-04-11 14:10
No, I think I just kept the rules in the stylesheet at the time.

**Comment by kara** [comment] 2024-10-25 18:23
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:23 UTC
