### ISSUE TITLE
Warning when using :host-context that is subselects_1.subselects[name] is not a function

### ISSUE THREAD

**Issue by starklord07** [GoogleChromeLabs/critters#104] opened 2022-05-10 05:59 UTC
I have updated my angular project to v13 and after getting this warning with `:host-context` selector that is `subselects_1.subselects[name] is not a function`.

I am using `critters@0.0.14` as part of `@angular-devkit/build-angular@13.1.2`. I guess the issue is related to #90.

I am getting the following warning.

`Generating index html...5 rules skipped due to selector errors:
  :host-context(.theme-themelight) .button.btn-primary -> subselects_1.subselects[name] is not a function
...`

**Comment by Dante1349** [comment] 2022-06-02 11:40
same issue with "@angular-devkit/build-angular": "13.3.7", "critters": "0.0.16", is there a workaround how to fix it?

**Comment by developit** [comment] 2022-06-02 23:02
Shouldn't be a workaround needed, since this is only a warning. It just means the generated critical CSS will not include the affected selector.

**Comment by starklord07** [comment] 2022-06-08 06:52
But is there any way to fix this warning ? I can recall, there was a similar issue #90 which was fixed.

**Comment by PowerKiKi** [comment] 2022-09-20 14:59
This is very likely to have the same root cause as #103, and IMHO should be close as duplicate.

**Comment by PowerKiKi** [comment] 2023-05-30 11:37
Solved by https://github.com/GoogleChromeLabs/critters/pull/124, which was released as 0.0.17.

@starklord07 , could you please close this issue ?

**Comment by kara** [comment] 2024-10-25 18:22
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:22 UTC
