### ISSUE TITLE
Unknown pseudo-class selector and Critters broke hash/nonce value

### ISSUE THREAD

**Issue by blephy** [GoogleChromeLabs/critters#33] opened 2019-03-13 23:18 UTC
Hi,

When i process webpack build with critters, i have 1 issue and 1 bug with another plugin : 

Issue : 

Critters do not include this pseudo-class selector

```1 rules skipped due to selector errors:
  ::-webkit-scrollbar-thumb -> unknown pseudo-class selector '::-webkit-scrollbar-thumb'
```

Bug : 

I use [CspHtmlWebpackPlugin](https://github.com/slackhq/csp-html-webpack-plugin) and some nonce or hash added (like with [webpack-subresource-integrity](https://github.com/waysact/webpack-subresource-integrity)). Even if i put the right order for the plugins like above, the integrity fail and assets fails to download.

```js
{
...
    new Critters({
      inlineFonts: true,
      preloadFonts: true,
      mergeStylesheets: true,
      keyframes: 'all',
      preload: 'swap',
      compress: true,
      logLevel: 'info'
    }),
    new CspHtmlWebpackPlugin(),
...
}
```

Seams like Critters is running after Webpack and doesn't use hooks inside a particular process build or something.. And Critters modifying JS / CSS content without re-running algorythm for new hash and nonce value previously injected in the html...
Am i clear ?

How can i get around this ?

Versions:
Webpack 4.29.6
Critters 2.3.0

Thanks

**Comment by kara** [comment] 2024-10-25 18:20
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:20 UTC
Labels: help wanted, webpack
