### ISSUE TITLE
Feature Request: Expose method `processCss` which returns inlined css only

### ISSUE THREAD

**Issue by Warxcell** [GoogleChromeLabs/critters#148] opened 2023-12-04 18:59 UTC
Use-case is to be able to use critters inside SSR, by processing only CSS and caching processed CSS - allowing the content to evolve independently from the processed CSS. Something like

```
let html = .... rendered html in ssr ...
const cacheKey = .... some logic ....
const criticalCSS = getInlinedCriticalCSSFromCache(cacheKey) ?? critters.processCss(html);

html = html.replace('</head>', criticalCSS + '</head>')
```

This will help also with https://github.com/GoogleChromeLabs/critters/issues/78

**Comment by kara** [comment] 2024-10-25 18:24
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:24 UTC
