### ISSUE TITLE
Fails to locate css for html files in subdirectories

### ISSUE THREAD

**Issue by Ansimorph** [GoogleChromeLabs/critters#19] opened 2018-12-04 05:12 UTC
The html file generated is in a subdirectory of the main output directory (`/project-root/dist/`):
`/project-root/dist/imprint/index.html`

The css is located in the output directory:
`/project-root/dist/styles.css`

So the html generated by webpack references relatively:
`<link href="../styles.css" rel="stylesheet">`

Critters resolves this as follows:
`filename = path.resolve(outputPath, href.replace(/^\//, ""));`

Leading to `path.resolve(/project-root/dist/../styles.css);` which generates the non-existant `/project-root/styles.css`

This is broken, because it tries to resolve relatively to the main output directory and not the real location of the html-file.

**Comment by Ansimorph** [comment] 2018-12-07 12:04
Setting a public path in webpack can circumvent the problem, because it generates absolute urls:
 
`output: {
        publicPath: "/"
}`

**Comment by developit** [comment] 2018-12-11 03:39
Nice catch! I always use publicPath since without it, client-side routing breaks resource paths. This should be pretty simple to fix.

**Comment by tlambrou** [comment] 2019-02-14 21:41
+1

**Comment by kara** [comment] 2024-10-25 18:20
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:20 UTC
Labels: enhancement, help wanted, good first issue, webpack
