### ISSUE TITLE
Duplicated styles when using `additionalStylesheets` option

### ISSUE THREAD

**Issue by rschristian** [GoogleChromeLabs/critters#88] opened 2021-11-10 10:39 UTC
The test added in #87 acts as a reproduction.

The basic gist of the issue is that the pattern used for `additionalStylesheets` can match the main CSS file, which causes its styles to be duplicated.

If we use a pattern like `*.css`, the sheet's contents will be added once from `additionalStylesheets()` and again from `embedLinkedStylesheets()`.

It seems that in the past the use of `cssnano` deduped these styles and hid the issue, though the current solution doesn't offer that same benefit.

Not sure whether this is a regression or just chance behavior that was relied upon.

**Comment by rschristian** [comment] 2021-11-11 21:41
Oops, looking like this might be misplaced. Going to close it for now as I'm not absolutely positive this is Critters' issue.

**Comment by rschristian** [comment] 2021-11-12 00:25
Nope, I was right, and found the issue.

In the past, assuming compression was not disabled, the sheet was processed with `cssnano`, which would remove duplicated styles. 

https://github.com/GoogleChromeLabs/critters/blob/85cae90858dfcf01d951f7cdc5e09907111e1b13/src/index.js#L245-L251

However, that's no longer the case, and it seems like the new compression is not capable of deduping. Is this intentional?

**Comment by developit** [comment] 2022-01-05 16:01
I've run into this as well in the past week.

**Comment by kara** [comment] 2024-10-25 18:21
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:21 UTC
