### ISSUE TITLE
Used css attribute selector gets removed by critters

### ISSUE THREAD

**Issue by michael-hein** [GoogleChromeLabs/critters#147] opened 2023-11-21 10:46 UTC
When using the Critter with a css selector [attribute contains](https://www.w3schools.com/cssref/sel_attr_contain.php) or [attribute starts with](https://www.w3schools.com/cssref/sel_attr_begin.php), then the Critter removes this selector even if its used.

``` ts
 const critters = new Critters({
    // optional configuration (see below)
  });

  const html = `
    <style>
      .red { color: red }
      .blue { color: blue }
      [class*=' test-'] {background-color: green}
    </style>
    <html>
    <body>
    <div class="blue test-green">I'm Blue</div>
    </body>
    </html>
  `;

  const inlined = await critters.process(html);

  console.log(inlined);
```
this results to 
```
Inlined 17 B (15% of original 109 B) of inline CSS.
Time 10.45

    <style>.blue{color:blue}</style>
    <html data-critters-container>
    <body>
    <div class="blue test-green">I'm Blue</div>
    </body>
    </html>
```
but the expectation is that `[class*=' test-'] {background-color: green}` should be still present.

**Comment by kara** [comment] 2024-10-25 18:24
Closing this issue because ownership of Critters has moved to the Nuxt team, who will be maintaining the project going forward. This repo is archived and won't receive any future updates.
 
If the issue is still relevant, please re-post it to the actively-maintained fork at https://github.com/danielroe/beasties.

**Closed by kara** 2024-10-25 18:24 UTC
